version: '3'
services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp

  fastapi:
    image: myapp
    command: python main.py
    ports:
      - '8000:8000'
    depends_on:
      - scraper
      - redis
      - celery
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  scraper:
    image: myapp
    command: python scrap_main.py

  celery:
    image: myapp
    command: celery -A celery_tasks worker --loglevel INFO -P threads -c 4 --uid=celeryuser
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:latest
    privileged: true
