version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - redis
      - celery
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6378

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A main.celery_app worker --loglevel=info
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6378

  redis:
    image: redis:latest
    ports:
      - '6378:6378'
